# Generated by Django 3.0.3 on 2020-11-21 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
    ]
